repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        # required to parse 'match' command
        args: ["--target-version", "py311"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: mypy
        types: [python]
        # exclude: "jobs"
        # args: [--ignore-missing-imports]
        args: [--strict-optional]
