bootstrap:


  features:
    # v2 adding as features, available as cli paramaters only atm (v1)
    # allowed values are parsed case-insensitive: [true|yes|YES|..] or [false|no|NO|..]
    # not as strings in quotes "yes" or 'yes'

    # default and recommended is: false
    #   in CDF 2022 support for this special-groups is not necessary anymore
    #   check 'bootstrap-cli deploy --help' for more info
    with-special-groups: false

    # default and recommended is: true
    with-raw-capability: true

    # new in v2 to configure prior (v1) hard-coded naming elements
    # Most of the naming-configurations don't have a functional effect, but affect
    # naming of Groups, Datasets and RAWDBs only.
    # All given feature values are reflecting the default values,
    # to support a smooth v1 migration.
    #
    # Recommended values for a new v2-project are given as comments!


    # default is: allprojects
    #   recommended is shorter: 'all'
    aggregated-level-name: all

    # default and recommended is: cdf
    #   supports empty-string ''
    group-prefix: cdf

    # default is: dataset
    #  recommended is shorter 'ds' or minimal ''
    #   supports empty-string ''
    dataset-suffix: ds

    # default is: rawdb
    #  recommended is shorter 'db' or minimal ''
    rawdb-suffix: db

    # default is" ['state']
    #   meant for separating the statestores from extractors from ingested data
    #   recommended: keep it or []
    #   more rawdbs can be configured at a later stage
    #   supports empty list [] for no additional variants
    rawdb-additional-variants:
      # provide more than one rawdb per ns-nodes
      # atm (v1) hardcoded is one additional rawdb
      - state
      # - pump # one more additional variant

  idp-cdf-mappings:
    # Prior (v1) named 'aad_mappings'.
    # Values for 'cdf-group' requires knowledge of resulting CDF Group names
    #
    # Now supporting multiple CDF Projects, like dev/test/prod
    # in one config. Optimization, to reduce redundant maintenance.
    # BOOTSTRAP_CDF_PROJECT env-variable is available and is used to select.
    - cdf-project: jfw-cpe-dev
      mappings:
      - cdf-group: cdf:root
        idp-source-id: bfd4306c-b5c6-48b7-9cc5-9b4c60936a85
        idp-source-name: All users
      - cdf-group: cdf:all:owner
        idp-source-id: 4442a284-afb8-45cb-bb4a-5c33e183e2ce
        idp-source-name: cdf_admin
      - cdf-group: cdf:all:read
        idp-source-id: 1ab49b52-67f7-46ba-aab8-77672566dcb7
        idp-source-name: cdf_read_all
      - cdf-group: cdf:uc:001:demand:read
        idp-source-id: d2682cbf-a7d6-414f-9d4f-54e5fab2f13e
        idp-source-name: jfw-cpe-dev

  namespaces:
    - ns-name: src
      # the description is not yet implemented in the namespace-level datasets
      description: Customer source-systems

      ns-nodes:
        - node-name: src:001:txt
          description: Sources 001; TXT
          # provide 'external-id' explicit for full control (i.e. of length) for the dataset
          # otherwise it will be autogenerated like the dataset name as '{node-name}[:{features.dataset-suffix}]'
          # 220425 pa: atm of release we have hard CDF limits for
          #    dataset.name        50 characters
          #    dataset.external_id 256 characters
          # violations will stop configuration loading and are reported on log-level
          external-id: src:001:txt
        - node-name: src:002:weather
          description: Sources 002; from Weather.com
          # external-id will be auto generated in this case
        - node-name: src:other
          description: Sources from anywhere
          # external-id will be auto generated in this case

#    - ns-name: in
#      description: End user data-input provided through deployed CDF driven solutions
#      ns-nodes:
#        - node-name: in:001:trade
#          description: Description about user inputs related to name
#          # external_id: in:001:trade

    - ns-name: uc
      description: Use Cases representing the data-products
      ns-nodes:
        - node-name: uc:001:demand
          description: Use Case 001; Supply and Demand

          # metadata will be merged into 'dataset.metadata'
          metadata:
            created: 220519
            generated: by cdf-config-hub script

          # shared-access is a powerful concept which **only** affects CDF Groups of type ':owner'.
          # Typically required for use-case groups, which have to read from multiple sources (nodes)
          # to apply the models and create the higher-value data-products in the uc dataset.
          #
          # It allows to grant additional 'read' or 'owner' access to other ns-nodes, across the 'namespaces'.
          # Allowing to easily maintain complex access-control needs, at the same time allowing a stable IdP mapping.
          shared-access:
            read:
              - node-name: src:001:txt
              - node-name: src:002:weather
            owner:
              - node-name: src:owner


# de-facto standards for CDF CogniteClient and logger configuration.
# Following the same parameter structure as the 'Cognite Python Extractor-Utilities'
# and 'Cognite DB Extractor' configuration.
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE_NAME}
  # host: https://${BOOTSTRAP_CDF_CLUSTER}.cognitedata.com/
  host: ${BOOTSTRAP_CDF_HOST}
  project: ${BOOTSTRAP_CDF_PROJECT}
  #
  # AAD IdP login credentials:
  #
  idp-authentication:
    client-id: ${BOOTSTRAP_IDP_CLIENT_ID}
    secret: ${BOOTSTRAP_IDP_CLIENT_SECRET}
    scopes:
      - ${BOOTSTRAP_IDP_SCOPES}
    token_url: ${BOOTSTRAP_IDP_TOKEN_URL}

logger:
  file:
    path: ./logs/create-dev-logs.log
    level: INFO
  console:
    level: INFO
