name: ci

on:
  # only during testing of the action from a different branch
  # pull_request:
  workflow_dispatch:
    # manually triggered only
    inputs:
      version:
        description: 'image version (tag)'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Version: ${{ inputs.version }}"

  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/docker/login-action#docker-hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

        # forked action. Original: buildpacks/github-actions/setup-pack
      - uses: cognitedata/github-actions/setup-pack@v4.8.1

      # image version then used by solutions-registry helm chart.
      # for github-action
      - run: pack/build.sh
        env:
          PUBLISH: true
          # VERSION: ${{ env.version }}
          VERSION: ${{ inputs.version }}
          IMAGE: cognite/bootstrap-cli

      - name: "Build and push Docker image for Azure Pipelines"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: cognite/bootstrap-cli:${{ inputs.version }}-azure