name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    # use main environment to login acr.
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # hardcoded for now, migrating gh-actions using dockerhub image
      # has to match action.yaml
      - run: echo "version=v3.0.0-beta.2-github"  >> $GITHUB_ENV

      # image version then used by solutions-registry helm chart.
      - run: pack/build.sh
        env:
          PUBLISH: true
          VERSION: ${{ env.version }}
          IMAGE: docker://cognite/bootstrap-cli
